### PR TITLE
Fixed an element missing error on hiding progress

### PR DESCRIPTION
**Pull request by kenji4569**
When hide the progress, and redirect somewhere just after, then I got an error for missing a reference element. I fixed it in the following way.

Thanks in advance.

### CODE REVIEW

**Comment by hnq90** [comment]
:+1: @milworm Please check this merge request.

**Comment by milworm** [comment]
Not sure I completely understand, but seems that you are trying to fix a problem that doesn't related to a progress-bar :( Is Progress.Component destroyed when you're calling #hide method?

**Comment by kenji4569** [comment]
> Is Progress.Component destroyed when you're calling #hide method?

Yes. I wrote a custom fetch function which calls Progress.show and Progress.hide transparently. And with the custom fetch function, I got the element missing error when I request an API and "redirect" (with react-router) another page just after the request succeeded.

**Comment by milworm** [comment]
@kenji4569 
ok, in this case it's all good and I don't see any reasons to merge your PR. Please read the documentation [https://github.com/milworm/react-progress-2](https://github.com/milworm/react-progress-2). You should simply put <Progress.Component> in the top-most component (e.g layout).

**Comment by kenji4569** [comment]
@milworm Ah, I got it. It worked when i put it in the top-most component. Sorry for my misunderstanding. Thanks!

**Comment by milworm** [comment]
no worries :)

**Pull request closed without merging**
